# Generated by Django 4.1.3 on 2022-11-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_alter_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="value",
            field=models.IntegerField(),
        ),
    ]
